import { ImGuiComponent } from '../types/imgui-component';

export const ImGuiComponents: ImGuiComponent[] = [
  {
    id: 0,
    name: 'Container',
    label: undefined,
    parent: undefined,
    children: undefined,
    selectable: false,
    value: undefined,
    properties: {
      height: 0,
      width: 0,
      padding: { x: 0, y: 0 },
      backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
      textColor: { r: 0, g: 0, b: 0, a: 0 },
      active: false,
    },
  },
  {
    id: 1,
    name: 'Column',
    label: undefined,
    parent: undefined,
    children: undefined,
    selectable: true,
    value: undefined,
    properties: {
      height: 0,
      width: 0,
      padding: { x: 0, y: 0 },
      backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
      textColor: { r: 0, g: 0, b: 0, a: 0 },
      active: false,
    },
  },
  {
    id: 2,
    name: 'Checkbox',
    label: undefined,
    parent: undefined,
    children: undefined,
    selectable: true,
    value: undefined,
    properties: {
      height: 0,
      width: 0,
      padding: { x: 0, y: 0 },
      backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
      textColor: { r: 0, g: 0, b: 0, a: 0 },
      active: false,
    },
  },
  {
    id: 3,
    name: 'Slider',
    label: undefined,
    parent: undefined,
    children: undefined,
    selectable: true,
    value: undefined,
    properties: {
      height: 0,
      width: 0,
      padding: { x: 0, y: 0 },
      backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
      textColor: { r: 0, g: 0, b: 0, a: 0 },
      active: false,
    },
  },
  {
    id: 4,
    name: 'Progress Bar',
    label: undefined,
    parent: undefined,
    children: undefined,
    selectable: true,
    value: undefined,
    properties: {
      height: 0,
      width: 0,
      padding: { x: 0, y: 0 },
      backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
      textColor: { r: 0, g: 0, b: 0, a: 0 },
      active: false,
    },
  },
  {
    id: 5,
    name: 'Text',
    label: undefined,
    parent: undefined,
    children: undefined,
    selectable: true,
    value: undefined,
    properties: {
      height: 0,
      width: 0,
      padding: { x: 0, y: 0 },
      backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
      textColor: { r: 0, g: 0, b: 0, a: 0 },
      active: false,
    },
  },
  {
    id: 6,
    name: 'Dropdown',
    label: undefined,
    parent: undefined,
    children: undefined,
    selectable: true,
    value: undefined,
    properties: {
      height: 0,
      width: 0,
      padding: { x: 0, y: 0 },
      backgroundColor: { r: 0, g: 0, b: 0, a: 0 },
      textColor: { r: 0, g: 0, b: 0, a: 0 },
      active: false,
    },
  },
];
